import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";
import { Amplify } from "aws-amplify";
import { onMessageListener, requestForToken } from "./firebase";
import outputs from '../amplify_outputs.json';
Amplify.configure(outputs);

// Mount React App
ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <div style={{ width: "100%" }}>
      <App />
    </div>
  </React.StrictMode>
);

// Firebase service worker registration
if ('serviceWorker' in navigator) {
  navigator.serviceWorker
    .register('/firebase-messaging-sw.js')
    .then((registration) => {
      console.log('Firebase SW registered:', registration);
      requestForToken(); // Get FCM token
    })
    .catch((err) => console.error('❌ Firebase SW registration failed:', err));
}

// PWA service worker registration (auto-generated by vite-plugin-pwa)
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('/sw.js')
      .then((registration) => {
        console.log('PWA SW registered:', registration);
      })
      .catch((err) => console.error('❌ PWA SW registration failed:', err));
  });
}

// Foreground message handling
onMessageListener().then((payload) => {
  console.log('🔔 Foreground message received:', payload);
}).catch((err) => {
  console.error('⚠️ Error listening to foreground messages:', err);
});
